version: '3'
services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: basic
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100


  springboot:
    depends_on:
      db:
        condition: service_healthy

    image: hcs4125/common-app:1.0
    ports:
      - "8078:8078"
    environment:
      ZK_ADDR: "localhost:2181"
      ARCUS_SERVICE_CODE: test
      SPRING_PORT: 8078
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/basic?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234